### PR TITLE
Update slurm-drmaa for libslurm26.

### PR DESCRIPTION
**Pull request by natefoo**

### CODE REVIEW

**Comment by natefoo** [comment]
@jmchilton any ideas on the remaining errors?

**Comment by jmchilton** [comment]
Wow - quite a bit broke.

**Comment by jmchilton** [comment]
Well not so much as it seemed. Is it possible the new slurm setup isn't quite right?

```
Exception: Failed to submit job, error was:
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /usr/lib/perl/5.18.2 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/bin/qsub line 50, <DATA> line 604.
BEGIN failed--compilation aborted at /usr/bin/qsub line 50, <DATA> line 604.
```
?

**Comment by natefoo** [comment]
Working on the additional issues in #139.

**Pull request merged**
