### PR TITLE
Fix more tests

### PR DESCRIPTION
**Pull request by natefoo**
Also, fix handling `conda_*` app config params and don't init conda with each test app launch.

### CODE REVIEW

**Comment by natefoo** [comment]
@jmchilton !!

**Comment by jmchilton** [comment]
What??

**Comment by natefoo** [comment]
Tests pass!!

**Comment by jmchilton** [comment]
Awesome - thanks! Want to make Planemo's pass next?

**Comment by natefoo** [comment]
Nooooooooooooooooooo

**Pull request merged**
