### PR TITLE
Drop Python 2.7 support in standard transport, drop Python 2.7 tests and fix Python 3.7 wheel install test, general test debugging enhancements

### PR DESCRIPTION
**Pull request by natefoo**
It's not going to work on 2.7 much longer anyway as galaxy-lib no longer supports 2.7.

### CODE REVIEW

**Comment by natefoo** [comment]
We can also just leave Paste and PasteScript in the `requirements.txt`, but they're unnecessary in a webless install.

**Comment by bgruening** [comment]
It seems we still have a paste-test that fails: https://travis-ci.org/github/galaxyproject/pulsar/jobs/717076970#L947

**Review by bgruening — COMMENTED** [review]
> [testenv:py27-install-wheel]

Should that be removed as well?

**Comment by natefoo** [comment]
> > [testenv:py27-install-wheel]
> 
> Should that be removed as well?

Yep, thanks.

**Comment by bgruening** [comment]
Cool, thanks Nate!

**Comment by jmchilton** [comment]
Looks good to me - thanks for all the work @natefoo !

**Pull request merged**
