### PR TITLE
Support for resuming staging transfers

### PR DESCRIPTION
**Pull request by natefoo**
Only implemented in the curl transport though.

Client changes in Galaxy in galaxyproject/galaxy#227

### CODE REVIEW

**Comment by jmchilton** [comment]
Any particular reason to add an option and not just have the curl down-loader just do this by default?

**Comment by natefoo** [comment]
I... no... err... I guess I just thought there might be some people who didn't want it enabled by... yeah, probably not.

Well, I know more about how Pulsar works now, anyway. :sob:

**Comment by natefoo** [comment]
@jmchilton Okay, got rid of the configurability.

**Comment by jmchilton** [comment]
Awesome - thanks! And sorry you had to learn so much Pulsar.

**Pull request merged**
